"""add_user_relationships

Revision ID: 032d18961462
Revises: 0a6e91aaaf73
Create Date: 2025-09-27 01:15:11.961282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032d18961462'
down_revision: Union[str, Sequence[str], None] = '0a6e91aaaf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to recreate the table to add NOT NULL constraint
    # First add the column as nullable
    op.add_column('accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Get the user_id for the test user 'hnamkung'
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM users WHERE username = 'hnamkung'"))
    user_id = result.fetchone()
    if user_id:
        user_id = user_id[0]
        # Update all existing accounts to belong to the test user
        connection.execute(sa.text(f"UPDATE accounts SET user_id = {user_id}"))
    
    # For SQLite, we need to recreate the table to make user_id NOT NULL
    # Create new table with user_id as NOT NULL
    op.create_table('accounts_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('owner', sa.Enum('HUN', 'SAEROM', 'YUEL', name='owner'), nullable=False),
        sa.Column('bank_name', sa.Enum('CHASE', 'VANGUARD', 'PNC', 'CHARLES_SCHWAB', 'Fidelity', 'CARTA', 'HEALTH_EQUITY', 'UMB', 'TOSS', 'MIRAE_ASSET', 'SHINHAN', 'KB', 'SHINHYUP', 'NONGHYUP', 'BNK', 'KSTECH', name='bankname'), nullable=False),
        sa.Column('account_name', sa.String(), nullable=False),
        sa.Column('account_country', sa.Enum('US', 'KOR', name='accountcountry'), nullable=False),
        sa.Column('account_currency_type', sa.Enum('USD', 'KRW', name='accountcurrencytype'), nullable=False),
        sa.Column('account_type', sa.Enum('Checking', 'Saving', 'STOCK', name='accounttype'), nullable=False),
        sa.Column('account_category', sa.Enum('PERSONAL', 'KOR_PSA', 'KOR_IRP', 'KOR_PENSION', 'US_401k', 'US_401k_PRETAX', 'US_401k_ROTH', 'US_401k_AFTERTAX', 'US_ROTH_IRA', 'HSA', 'RSU', name='accountcategory'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Copy data from old table to new table
    connection.execute(sa.text("""
        INSERT INTO accounts_new (id, order, user_id, owner, bank_name, account_name, account_country, account_currency_type, account_type, account_category)
        SELECT id, order, user_id, owner, bank_name, account_name, account_country, account_currency_type, account_type, account_category
        FROM accounts
    """))
    
    # Drop old table and rename new table
    op.drop_table('accounts')
    op.rename_table('accounts_new', 'accounts')
    
    # Create indexes
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###
