"""create transactions table

Revision ID: de1fe394c528
Revises: be1e9249f0a4
Create Date: 2025-08-03 12:22:23.723931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de1fe394c528"
down_revision: Union[str, Sequence[str], None] = "be1e9249f0a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DEPOSIT",
                "WITHDRAWAL",
                "BUY",
                "SELL",
                "FX",
                "BALANCE_SNAPSHOT",
                name="transactiontype",
            ),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column("fx_rate", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("transactions")
